### ISSUE TITLE
How to run your navier_stokes3d.py using google colab?

### ISSUE THREAD

**Issue by xgxgnpu** [stnamjef/SPINN#3]
Thanks for your great work.It is a really important paper for accelarating the training of PINNs.

**Comment by stnamjef** [comment]
Thanks for your interest in our work! Unfortunately, we do not provide a demo (.ipynb file) for the Navier Stokes experiment, but you can always run the script file to reproduce the results. Please try running the navier_stokes3d.sh file in the scripts folder, and let us know if you have any problems running the code. Thanks!

**Comment by xgxgnpu** [comment]
> Thanks for your interest in our work! Unfortunately, we do not provide a demo (.ipynb file) for the Navier Stokes experiment, but you can always run the script file to reproduce the results. Please try running the navier_stokes3d.sh file in the scripts folder, and let us know if you have any problems running the code. Thanks!

Thank you for your nice reply! I tried using your SPINN to solve my own problem, simulating a navier_stokes3d with a time interval of 0 to 30s. I've successfully written and run the code, but am not very happy with the accuracy. Could you please give some effective suggestions on improving the accuracy of SPINN?

Btw ,can I have your email address? Thank you very much in advance.
Have a nice day!
Xiongxiong

**Comment by jwcho5576** [comment]
Hello, could you please contact me via email at [jwcho000@g.skku.edu]?

**Comment by xgxgnpu** [comment]
> Hello, could you please contact me via email at [[jwcho000@g.skku.edu](mailto:jwcho000@g.skku.edu)]?

Sure,thanks!
