### ISSUE TITLE
data_dir for NS4D？

### ISSUE THREAD

**Issue by wangguan1995** [stnamjef/SPINN#4]
Hi there，
I found there are a script and data for NS3D, how can I acquire data for 4D? 
As I assume, it will be (x,y,z,t)?
Thanks

**Comment by wangguan1995** [comment]
Talking about this:
https://github.com/stnamjef/SPINN/blob/main/scripts/navier_stokes4d.sh

**Comment by jwcho5576** [comment]
Sorry for the late reply.

We used a manufactured solution for NS4d so there's no actual data 'file' for this equation.

You can find the code for generating the manufactured data in SPINN/utils/data_generators.py, line 364 _spinn_train_generator_navier_stokes4d.

**Comment by wangguan1995** [comment]
Thanks a lot, the generator works!
